-- Snapshot: 2026-07-31; 89 current 25th-Knesset members from the official Knesset OData query.
-- Source: https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_PersonToPosition()?%24filter=KnessetNum%20eq%2025%20and%20PositionID%20eq%2043%20and%20IsCurrent%20eq%20true&%24expand=KNS_Person&%24format=json&%24top=200

INSERT INTO recipients (id, type, email, whatsapp, website, is_active) VALUES
  (30749, 'politician', 'mabutbul@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30749', 1),
  (30601, 'politician', 'yazulai@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30601', 1),
  (30765, 'politician', 'urielb@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30765', 1),
  (2291, 'politician', 'aderey@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=2291', 1),
  (30770, 'politician', 'jtaieb@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30770', 1),
  (30470, 'politician', 'malkielim@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30470', 1),
  (532, 'politician', 'yedelstein@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=532', 1),
  (30300, 'politician', 'amiro@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30300', 1),
  (23558, 'politician', 'dbitan@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=23558', 1),
  (30700, 'politician', 'nbarkat@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30700', 1),
  (4395, 'politician', 'davraham@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=4395', 1),
  (30701, 'politician', 'okatz@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30701', 1),
  (468, 'politician', 'yiskatz@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=468', 1),
  (12951, 'politician', 'ylevin@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=12951', 1),
  (965, 'politician', 'bnetanyahu@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=965', 1),
  (30704, 'politician', 'shlomok@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30704', 1),
  (30811, 'politician', 'ibengvir@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30811', 1),
  (30814, 'politician', 'amaaoz@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30814', 1),
  (30812, 'politician', 'srothman@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30812', 1),
  (30752, 'politician', 'hak_taha@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30752', 1),
  (30713, 'politician', 'mabas@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30713', 1),
  (30807, 'politician', 'gkariv@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30807', 1),
  (23641, 'politician', 'yakova@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=23641', 1),
  (526, 'politician', 'mgafni@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=526', 1),
  (30776, 'politician', 'vbeliak@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30776', 1),
  (30691, 'politician', 'rbenbarak@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30691', 1),
  (30820, 'politician', 'hak_davidson@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30820', 1),
  (30777, 'politician', 'mturpaz@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30777', 1),
  (23597, 'politician', 'cohenmeir@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=23597', 1),
  (30720, 'politician', 'ylahav@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30720', 1),
  (23632, 'politician', 'mickeylevy@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=23632', 1),
  (23594, 'politician', 'ylapid@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=23594', 1),
  (30695, 'politician', 'yoavse@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30695', 1),
  (23591, 'politician', 'sterne@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=23591', 1),
  (30657, 'politician', 'bgantz@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30657', 1),
  (4397, 'politician', 'zelkin@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=4397', 1),
  (30683, 'politician', 'ctropper@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30683', 1),
  (30682, 'politician', 'mbiton@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30682', 1),
  (30694, 'politician', 'aschuster@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30694', 1),
  (30835, 'politician', 'bbismut@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30835', 1),
  (30831, 'politician', 'edalal@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30831', 1),
  (30861, 'politician', 'shdanino@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30861', 1),
  (30772, 'politician', 'nvaturi@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30772', 1),
  (30842, 'politician', 'chmelavitzky@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30842', 1),
  (30853, 'politician', 'mosaada@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30853', 1),
  (30832, 'politician', 'erevivo@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30832', 1),
  (30847, 'politician', 'yvaserlof@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30847', 1),
  (30830, 'politician', 'ohtal@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30830', 1),
  (30852, 'politician', 'mosolomon@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30852', 1),
  (30859, 'politician', 'tzfoghel@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30859', 1),
  (30717, 'politician', 'osofer@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30717', 1),
  (30840, 'politician', 'waleed.alh@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30840', 1),
  (30843, 'politician', 'yschogarat@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30843', 1),
  (30066, 'politician', 'aymanod@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30066', 1),
  (560, 'politician', 'atibi@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=560', 1),
  (30719, 'politician', 'ocassif@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30719', 1),
  (30854, 'politician', 'nshiri@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30854', 1),
  (427, 'politician', 'aliberman@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=427', 1),
  (30722, 'politician', 'esova@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30722', 1),
  (12938, 'politician', 'amarh@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=12938', 1),
  (30121, 'politician', 'odedfo@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30121', 1),
  (30867, 'politician', NULL, NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30867', 1),
  (30868, 'politician', 'hak_jmishraki@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30868', 1),
  (30839, 'politician', 'hak_diluz@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30839', 1),
  (30710, 'politician', 'kallner@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30710', 1),
  (30711, 'politician', 'ahalevi@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30711', 1),
  (30876, 'politician', 'oshkalim@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30876', 1),
  (30877, 'politician', 'hak_passal@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30877', 1),
  (30879, 'politician', 'hak_guetta@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30879', 1),
  (30881, 'politician', 'yalevi@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30881', 1),
  (30880, 'politician', 'hak_boaron@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30880', 1),
  (30799, 'politician', 'mbuskila@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30799', 1),
  (30893, 'politician', 'abbed@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30893', 1),
  (30857, 'politician', 'abene@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30857', 1),
  (30874, 'politician', 'tzvisuccot@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30874', 1),
  (30846, 'politician', 'ygoldknop@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30846', 1),
  (30894, 'politician', 'samirb@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30894', 1),
  (30693, 'politician', 'eginzburg@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30693', 1),
  (22151, 'politician', 'akramh@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=22151', 1),
  (11835, 'politician', 'umaklev@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=11835', 1),
  (563, 'politician', 'mporush@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=563', 1),
  (30671, 'politician', 'ytesler@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30671', 1),
  (30804, 'politician', 'chbiton@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30804', 1),
  (1056, 'politician', 'ymargi@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=1056', 1),
  (28513, 'politician', 'ybentzur@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=28513', 1),
  (30672, 'politician', 'ypindrus@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30672', 1),
  (30873, 'politician', 'hak_malul@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30873', 1),
  (30916, 'politician', 'ohaim@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30916', 1),
  (30917, 'politician', 'hak_abuelh@knesset.gov.il', NULL, 'https://main.knesset.gov.il/mk/Pages/MKPersonalDetails.aspx?MKID=30917', 1);

INSERT INTO recipient_translations (recipient_id, locale, name) VALUES
  (30749, 'he', 'משה אבוטבול'),
  (30601, 'he', 'ינון אזולאי'),
  (30765, 'he', 'אוריאל בוסו'),
  (2291, 'he', 'אריה מכלוף דרעי'),
  (30770, 'he', 'יוסף טייב'),
  (30470, 'he', 'מיכאל מלכיאלי'),
  (532, 'he', 'יולי יואל אדלשטיין'),
  (30300, 'he', 'אמיר אוחנה'),
  (23558, 'he', 'דוד ביטן'),
  (30700, 'he', 'ניר ברקת'),
  (4395, 'he', 'אבי דיכטר'),
  (30701, 'he', 'אופיר כץ'),
  (468, 'he', 'ישראל כץ'),
  (12951, 'he', 'יריב לוין'),
  (965, 'he', 'בנימין נתניהו'),
  (30704, 'he', 'שלמה קרעי'),
  (30811, 'he', 'איתמר בן גביר'),
  (30814, 'he', 'אבי מעוז'),
  (30812, 'he', 'שמחה רוטמן'),
  (30752, 'he', 'ווליד טאהא'),
  (30713, 'he', 'מנסור עבאס'),
  (30807, 'he', 'גלעד קריב'),
  (23641, 'he', 'יעקב אשר'),
  (526, 'he', 'משה גפני'),
  (30776, 'he', 'ולדימיר בליאק'),
  (30691, 'he', 'רם בן ברק'),
  (30820, 'he', 'סימון דוידסון'),
  (30777, 'he', 'משה טור פז'),
  (23597, 'he', 'מאיר כהן'),
  (30720, 'he', 'יוראי להב הרצנו'),
  (23632, 'he', 'מיקי לוי'),
  (23594, 'he', 'יאיר לפיד'),
  (30695, 'he', 'יואב סגלוביץ'''),
  (23591, 'he', 'אלעזר שטרן'),
  (30657, 'he', 'בנימין גנץ'),
  (4397, 'he', 'זאב אלקין'),
  (30683, 'he', 'חילי טרופר'),
  (30682, 'he', 'מיכאל מרדכי ביטון'),
  (30694, 'he', 'אלון שוסטר'),
  (30835, 'he', 'בועז ביסמוט'),
  (30831, 'he', 'אלי דלל'),
  (30861, 'he', 'שלום דנינו'),
  (30772, 'he', 'ניסים ואטורי'),
  (30842, 'he', 'חנוך דב מלביצקי'),
  (30853, 'he', 'משה סעדה'),
  (30832, 'he', 'אליהו רביבו'),
  (30847, 'he', 'יצחק שמעון וסרלאוף'),
  (30830, 'he', 'אוהד טל'),
  (30852, 'he', 'משה סולומון'),
  (30859, 'he', 'צביקה פוגל'),
  (30717, 'he', 'אופיר סופר'),
  (30840, 'he', 'ואליד אלהואשלה'),
  (30843, 'he', 'יאסר חוג''יראת'),
  (30066, 'he', 'איימן עודה'),
  (560, 'he', 'אחמד טיבי'),
  (30719, 'he', 'עופר כסיף'),
  (30854, 'he', 'נאור שירי'),
  (427, 'he', 'אביגדור ליברמן'),
  (30722, 'he', 'יבגני סובה'),
  (12938, 'he', 'חמד עמאר'),
  (30121, 'he', 'עודד פורר'),
  (30867, 'he', 'יצחק קרויזר'),
  (30868, 'he', 'יונתן מישרקי'),
  (30839, 'he', 'דן אילוז'),
  (30710, 'he', 'אריאל קלנר'),
  (30711, 'he', 'עמית הלוי'),
  (30876, 'he', 'אושר שקלים'),
  (30877, 'he', 'משה פסל'),
  (30879, 'he', 'ששון ששי גואטה'),
  (30881, 'he', 'ירון לוי'),
  (30880, 'he', 'אביחי אברהם בוארון'),
  (30799, 'he', 'מישל בוסקילה'),
  (30893, 'he', 'עפיף עבד'),
  (30857, 'he', 'עמיחי אליהו'),
  (30874, 'he', 'צבי ידידיה סוכות'),
  (30846, 'he', 'יצחק גולדקנופ'),
  (30894, 'he', 'סמיר בן סעיד'),
  (30693, 'he', 'איתן גינזבורג'),
  (22151, 'he', 'אכרם חסון'),
  (11835, 'he', 'אורי מקלב'),
  (563, 'he', 'מאיר פרוש'),
  (30671, 'he', 'יעקב טסלר'),
  (30804, 'he', 'חיים ביטון'),
  (1056, 'he', 'יעקב מרגי'),
  (28513, 'he', 'יואב בן צור'),
  (30672, 'he', 'יצחק פינדרוס'),
  (30873, 'he', 'ארז מלול'),
  (30916, 'he', 'עוז חיים'),
  (30917, 'he', 'מוחמד אבו אל היג''א');
